# What host should be the Grav website accessible from?
app_host: amaury.carrade.eu

# Where the Grav website will be installed
grav_root: "{{ www_root }}/carrade/amaury"

# Where the original Grav user folder will be copied while cloning the user repo. This
# folder will be deleted afterwards.
grav_user_backup: "{{ grav_root }}/__ansible_default_user_backup"

# The repository containing the user folder (or parts of it), typically synced with
# the git-sync plugin.
grav_user_repo: https://github.com/AmauryCarrade/amaury.carrade.eu.git
grav_user_repo_branch: main

# The repository containing the theme to use. The theme name will be the folder name
# where the theme will be stored, it must match the internal name exactly.
grav_theme_repo: https://github.com/AmauryCarrade/grav-theme-amaury-carrade.git
grav_theme_repo_branch: main
grav_theme_name: amaury-carrade

# Grav plugins automatically installed. These must be valid GPM slugs. Existing plugins will not
# be uninstalled (e.g. if installed through the Admin plugin or GPM directly), but it would be a
# good idea to add them here for the future.
grav_plugins:
  # Core
  - problems
  - error
  - flex-objects
  - form
  - email
  - login
  - admin

  # Just for me
  - random
  - admin-addon-media-rename
  - readingtime
  - tntsearch
  - git-sync
  - page-toc
  - feed
  - taxonomylist
  - pagination

tools_base: https://outils.carrade.eu

# Permanent redirects added to nginx configuration
#  from: the path to be redirected. Regular expression (auto-prefixed with ^)
#  to: the path or URL to redirect to.
#  rewrite: if set, will use nginx rewriting instead of return 302. You then can use regular expressions in path/URLs.
#           If falsy or unset, no rewrite. If set, should be the rewrite regex. Default unset.
#  base: if true, will redirect all sub-paths too. Default false.
#  permanent: if true, 301, else 302 (temporary redirect). Default true.
app_redirections:
  # Internal redirections
  - from: /about
    to: /meta
  - from: /legal
    to: /meta
  - from: /apropos
    to: /meta
  - from: /a-propos
    to: /meta

  # Removed pages - Donation links in footer now.
  - from: /don
    to: /meta
  - from: /donation
    to: /meta
  - from: /donner
    to: /meta

  # Alice's memoire
  - from: /mémoire-alice(-thomas)?
    to: /memoire-alice-thomas
  - from: /m(e|é)moire-?alice(thomas)?
    to: /memoire-alice-thomas
  - from: /alice(-?thomas)?
    to: /memoire-alice-thomas

  # Companion websites
  - from: /PR
    to: https://free.carrade.eu
  - from: /links
    to: https://shaarli.amaury.carrade.eu/$1
    rewrite: /links(?:/(.*))?
    base: true
  - from: /tea
    to: https://my-tea.party/$1
    rewrite: /tea(?:/(.*))?
    base: true

  # Tools, now on another domain
  - from: /tools
    to: "{{ tools_base }}"
  - from: /upload
    to: "{{ tools_base }}/upload"
  - from: /minecraft
    to: "{{ tools_base }}/minecraft/$1"
    rewrite: /minecraft(?:/(.*))?
    base: true
  - from: /mumble
    to: "{{ tools_base }}/mumble/$1"
    rewrite: /mumble(?:/(.*))?
    base: true
  - from: /tools
    to: "{{ tools_base }}/tools/$1"
    rewrite: /tools(?:/(.*))?
    base: true
  - from: /uuid
    to: "{{ tools_base }}/minecraft/history"
  - from: /ping
    to: "{{ tools_base }}/minecraft/ping"
  - from: /bukkit/permissions
    to: "{{ tools_base }}/bukkit/permissions"
  - from: /tools/generators/bukkit/permissions.html
    to: "{{ tools_base }}/bukkit/permissions"
  - from: /chat_highlighter
    to: "{{ tools_base }}/chat_highlighter"
  - from: /chat-highlighter
    to: "{{ tools_base }}/chat_highlighter"
  - from: /chat_highlighter/json
    to: "{{ tools_base }}/chat_highlighter/json"
  - from: /redirects
    to: "{{ tools_base }}/redirects"
  - from: /redirects/json
    to: "{{ tools_base }}/redirects/json"
  - from: /articles/mumble
    to: "{{ tools_base }}/articles/mumble"
  - from: /programmation/commencer
    to: "{{ tools_base }}/programmation/commencer"
